version: "3.9"

services:
  redis:
    image: redis:7.0-alpine
    restart: always
    ports:
      - "6379:6379"
    expose:
      - "6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass password --maxmemory-policy noeviction
    volumes:
      - radquestRedisData:/data

  redis-commander:
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "8081:8081"

  postgres:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    expose:
      - "5433"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - radquestPostgresData:/data

volumes:
  radquestPostgresData:
    driver: local
  radquestRedisData:
    driver: local
