{{- if .Values.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "radquest-transaction-stream.fullname" . }}-metrics
  labels:
    {{- include "radquest-transaction-stream.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.metrics.port }}
    name: metrics
    targetPort: {{ .Values.metrics.port }}
  selector:
    {{- include "radquest-transaction-stream.selectorLabels" . | nindent 4 }}
{{- end }}
{{- if .Values.pm2_metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "radquest-transaction-stream.fullname" . }}-pm2-metrics
  labels:
    {{- include "radquest-transaction-stream.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.pm2_metrics.port }}
    name: pm2-metrics
    targetPort: {{ .Values.pm2_metrics.port }}
  selector:
    {{- include "radquest-transaction-stream.selectorLabels" . | nindent 4 }}
{{- end }}