export const LandingPopupSchema = {
  Ticket: 'ticket',
  UserReferral: 'userreferral',
  Influencer: 'influencer',
  Paid: 'paid'
} as const

export type LandingPopupSchema = (typeof LandingPopupSchema)[keyof typeof LandingPopupSchema]

export const UtmSourceLanding = {
  'Twitter-geo1a': { schema: LandingPopupSchema.Paid, data: { source: 'X' } },
  'Twitter-geo1b': { schema: LandingPopupSchema.Paid, data: { source: 'X' } },
  'Twitter-RT-geo1': { schema: LandingPopupSchema.Paid, data: { source: 'X' } },
  'Twitter-geo2a': { schema: LandingPopupSchema.Paid, data: { source: 'X' } },
  'Twitter-geo2b': { schema: LandingPopupSchema.Paid, data: { source: 'X' } },
  'Twitter-RT-geo2': { schema: LandingPopupSchema.Paid, data: { source: 'X' } },
  'Twitter-geo3a': { schema: LandingPopupSchema.Paid, data: { source: 'X' } },
  'Twitter-geo3b': { schema: LandingPopupSchema.Paid, data: { source: 'X' } },
  'Twitter-RT-geo3': { schema: LandingPopupSchema.Paid, data: { source: 'X' } },
  'Reddit-geo1a': { schema: LandingPopupSchema.Paid, data: { source: 'Reddit' } },
  'Reddit-RT-geo1': { schema: LandingPopupSchema.Paid, data: { source: 'Reddit' } },
  'Reddit-geo2a': { schema: LandingPopupSchema.Paid, data: { source: 'Reddit' } },
  'Reddit-RT-geo2': { schema: LandingPopupSchema.Paid, data: { source: 'Reddit' } },
  'Reddit-geo3a': { schema: LandingPopupSchema.Paid, data: { source: 'Reddit' } },
  'Reddit-RT-geo3': { schema: LandingPopupSchema.Paid, data: { source: 'Reddit' } },
  'Meta-RT-geo1': { schema: LandingPopupSchema.Paid, data: { source: 'Facebook' } },
  'Meta-RT-geo2': { schema: LandingPopupSchema.Paid, data: { source: 'Facebook' } },
  'Meta-RT-geo3': { schema: LandingPopupSchema.Paid, data: { source: 'Facebook' } },
  'Brave-Takeover-geo1-and-geo2': { schema: LandingPopupSchema.Paid, data: { source: 'Brave' } },
  'Brave-Push-geo1-Desktop': { schema: LandingPopupSchema.Paid, data: { source: 'Brave' } },
  'Brave-Push-geo1-Android': { schema: LandingPopupSchema.Paid, data: { source: 'Brave' } },
  'Brave-Push-geo1-iOS': { schema: LandingPopupSchema.Paid, data: { source: 'Brave' } },
  'Brave-Push-geo2-Desktop': { schema: LandingPopupSchema.Paid, data: { source: 'Brave' } },
  'Brave-Push-geo2-Android': { schema: LandingPopupSchema.Paid, data: { source: 'Brave' } },
  'Brave-Push-geo2-iOS': { schema: LandingPopupSchema.Paid, data: { source: 'Brave' } },
  'Brave-Push-geo3-Desktop': { schema: LandingPopupSchema.Paid, data: { source: 'Brave' } },
  'Brave-Push-geo3-Android': { schema: LandingPopupSchema.Paid, data: { source: 'Brave' } },
  'Brave-Push-geo3-iOS': { schema: LandingPopupSchema.Paid, data: { source: 'Brave' } },
  'CoinMarketCap-Banner-Website': {
    schema: LandingPopupSchema.Paid,
    data: { source: 'CoinMarketCap' }
  },
  'CoinGecko-Banner-Website': { schema: LandingPopupSchema.Paid, data: { source: 'CoinGecko' } },
  'CoinGecko-Banner-App': { schema: LandingPopupSchema.Paid, data: { source: 'CoinGecko' } },
  'CoinDesk-Banner-Website': { schema: LandingPopupSchema.Paid, data: { source: 'CoinGecko' } },
  'CoinTelegraph-Sidebar': { schema: LandingPopupSchema.Paid, data: { source: 'CoinTelegraph' } },
  'CoinTelegraph-Leaderboard': {
    schema: LandingPopupSchema.Paid,
    data: { source: 'CoinTelegraph' }
  },
  'CoinTelegraph-Between': { schema: LandingPopupSchema.Paid, data: { source: 'CoinTelegraph' } },
  'CoinTelegraph-Mainpage': { schema: LandingPopupSchema.Paid, data: { source: 'CoinTelegraph' } },
  'DeCrypt-Banner-Website': { schema: LandingPopupSchema.Paid, data: { source: 'DeCrypt' } },
  'CryptoRank-Banner-Website': { schema: LandingPopupSchema.Paid, data: { source: 'CryptoRank' } },
  'CryptoRank-Native-Banner': { schema: LandingPopupSchema.Paid, data: { source: 'CryptoRank' } },
  'BTCEcho-Banner-Website': { schema: LandingPopupSchema.Paid, data: { source: 'BTCEcho' } },
  CoinDesk: { schema: LandingPopupSchema.Paid, data: { source: 'CoinDesk' } },
  CoinTelegraph: { schema: LandingPopupSchema.Paid, data: { source: 'CoinTelegraph' } },
  DeCrypt: { schema: LandingPopupSchema.Paid, data: { source: 'DeCrypt' } },
  BlockWorks: { schema: LandingPopupSchema.Paid, data: { source: 'BlockWorks' } },
  BTCEcho: { schema: LandingPopupSchema.Paid, data: { source: 'BTCEcho' } },
  CoinZilla: { schema: LandingPopupSchema.Paid, data: { source: 'CoinZilla' } },
  Blockmates: { schema: LandingPopupSchema.Paid, data: { source: 'Blockmates' } },
  CoinAcademy: { schema: LandingPopupSchema.Paid, data: { source: 'CoinAcademy' } },
  JournalDuCoin: { schema: LandingPopupSchema.Paid, data: { source: 'JournalDuCoin' } },
  CoinGape: { schema: LandingPopupSchema.Paid, data: { source: 'CoinGape' } },
  CryptoPotato: { schema: LandingPopupSchema.Paid, data: { source: 'CryptoPotato' } },
  CryptoNews: { schema: LandingPopupSchema.Paid, data: { source: 'CryptoNews' } },
  Techtimes: { schema: LandingPopupSchema.Paid, data: { source: 'Techtimes' } },
  CryptoDaily: { schema: LandingPopupSchema.Paid, data: { source: 'CryptoDaily' } },
  Galxe: { schema: LandingPopupSchema.Paid, data: { source: 'Galxe' } },
  Zealy: { schema: LandingPopupSchema.Paid, data: { source: 'Zealy' } },
  Announcement: { schema: LandingPopupSchema.Paid, data: { source: 'Radix' } },
  BlockWorks2: { schema: LandingPopupSchema.Paid, data: { source: 'BlockWorks' } },
  TLDR: { schema: LandingPopupSchema.Paid, data: { source: 'TLDR' } },
  Ethermail: { schema: LandingPopupSchema.Paid, data: { source: 'Ethermail' } },
  Blocmates: { schema: LandingPopupSchema.Paid, data: { source: 'Blocmates' } },
  CryptoRank: { schema: LandingPopupSchema.Paid, data: { source: 'CryptoRank' } },
  BeInCrypto: { schema: LandingPopupSchema.Paid, data: { source: 'BeInCrypto' } },
  Mycelium: { schema: LandingPopupSchema.Paid, data: { source: 'Mycelium' } },
  altcoindaily: { schema: LandingPopupSchema.Influencer, data: { influencer: 'Altcoin Daily' } },
  datadash: { schema: LandingPopupSchema.Influencer, data: { influencer: 'Data Dash' } },
  larkdavis: { schema: LandingPopupSchema.Influencer, data: { influencer: 'Lark Davis' } },
  milesdeutscher: {
    schema: LandingPopupSchema.Influencer,
    data: { influencer: 'Miles Deutscher' }
  },
  ashcrypto: { schema: LandingPopupSchema.Influencer, data: { influencer: 'Ash Crypto' } },
  cryptocasey: { schema: LandingPopupSchema.Influencer, data: { influencer: 'Crypto Casey' } },
  sincity: { schema: LandingPopupSchema.Influencer, data: { influencer: 'Sin City Crypto' } },
  paulbarron: { schema: LandingPopupSchema.Influencer, data: { influencer: 'Paul Barron' } },
  voskcoin: { schema: LandingPopupSchema.Influencer, data: { influencer: 'Vosk Coin' } },
  conorkenny: { schema: LandingPopupSchema.Influencer, data: { influencer: 'Conor Kenny' } },
  nobs: { schema: LandingPopupSchema.Influencer, data: { influencer: 'No Bs Crypto' } },
  catalinacastro: {
    schema: LandingPopupSchema.Influencer,
    data: { influencer: 'Catalina Castro' }
  },
  voepa: { schema: LandingPopupSchema.Influencer, data: { influencer: 'Voepa Bitcoin' } },
  academia: { schema: LandingPopupSchema.Influencer, data: { influencer: 'Academia Cripto' } },
  cryptotony: { schema: LandingPopupSchema.Influencer, data: { influencer: 'Crypto Tony' } },
  posty: { schema: LandingPopupSchema.Influencer, data: { influencer: 'PostyXBT' } },
  backwards: { schema: LandingPopupSchema.Influencer, data: { influencer: '0xbackwards' } },
  crg: { schema: LandingPopupSchema.Influencer, data: { influencer: 'CRG' } },
  teddy: { schema: LandingPopupSchema.Influencer, data: { influencer: 'Teddy' } },
  kong: { schema: LandingPopupSchema.Influencer, data: { influencer: 'Kong Trading' } },
  monk: { schema: LandingPopupSchema.Influencer, data: { influencer: 'The Crypto Monk' } },
  timeless: { schema: LandingPopupSchema.Influencer, data: { influencer: 'TimelessBeing' } },
  rasgard: { schema: LandingPopupSchema.Influencer, data: { influencer: 'Rasgard' } },
  otsukimi: { schema: LandingPopupSchema.Influencer, data: { influencer: 'Otsukimi' } },
  groot: { schema: LandingPopupSchema.Influencer, data: { influencer: 'GROOT' } },
  coinnews: { schema: LandingPopupSchema.Influencer, data: { influencer: 'iWantCoinNews' } },
  murfski: { schema: LandingPopupSchema.Influencer, data: { influencer: 'Murfski' } },
  ladyofcrypto: { schema: LandingPopupSchema.Influencer, data: { influencer: 'Lady of Crypto' } },
  smartape: { schema: LandingPopupSchema.Influencer, data: { influencer: 'The Smart Ape' } },
  aiden: { schema: LandingPopupSchema.Influencer, data: { influencer: 'Aiden DeFi' } },
  zeus: { schema: LandingPopupSchema.Influencer, data: { influencer: 'Crypto Zeus' } },
  maria: { schema: LandingPopupSchema.Influencer, data: { influencer: 'Crypto Maria' } },
  pushka: { schema: LandingPopupSchema.Influencer, data: { influencer: 'Roman Pushka' } },
  dad: { schema: LandingPopupSchema.Influencer, data: { influencer: 'Crypto Dad' } },
  leo: { schema: LandingPopupSchema.Influencer, data: { influencer: 'Leonardo Vecchio' } },
  smartinvestor: {
    schema: LandingPopupSchema.Influencer,
    data: { influencer: 'SMART INVESTOR' }
  },
  sozluk: { schema: LandingPopupSchema.Influencer, data: { influencer: 'Kripto Sözlük' } },
  atamert: { schema: LandingPopupSchema.Influencer, data: { influencer: 'Atamert Uysaler' } },
  hamed: { schema: LandingPopupSchema.Influencer, data: { influencer: 'Amr Hamed' } },
  crypto2go: { schema: LandingPopupSchema.Influencer, data: { influencer: 'Bitcoin2Go' } },
  hunter: { schema: LandingPopupSchema.Influencer, data: { influencer: 'Coin Hunter' } },
  arreat: { schema: LandingPopupSchema.Influencer, data: { influencer: 'Arreat Summit' } },
  andrew: { schema: LandingPopupSchema.Influencer, data: { influencer: 'Andrew Moh' } },
  wrubel: { schema: LandingPopupSchema.Influencer, data: { influencer: 'Michael Wrubel' } },
  magcoin: { schema: LandingPopupSchema.Influencer, data: { influencer: 'BMS' } },
  digitalassetnews: {
    schema: LandingPopupSchema.Influencer,
    data: { influencer: 'Digital Asset News' }
  },
  wendy: { schema: LandingPopupSchema.Influencer, data: { influencer: 'WendyO' } }
} as const
