image:
  repository: docker.io/radixdlt/radquest-swap
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets:
  - name: dockerhub-dev-letty-swap

replicaCount: 1

metrics:
  enabled: false
  port: 9209

nameOverride: "letty-swap"

fullnameOverride: "letty-swap"

params:

secrets: {}

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: ""
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

docker:
  secrets:
    name: docker.io/radixdlt

# Set it to true if you want to secret to be deployed.
docker_secret: 
    enabled: true
