environments:
  demo: {}
  pr: {}
---
helmDefaults:
  verify: false
  wait: true
  timeout: 60
  recreatePods: false
  force: false
  createNamespace: false
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: rdx-works
    url: https://raw.githubusercontent.com/radixdlt/helm-charts/master/
    username: {{ requiredEnv "HELM_GH_USER" }}
    password: {{ requiredEnv "HELM_GH_PASS" }}
  - name: kubesphere
    url: https://charts.kubesphere.io/main

releases:
  - name: dockerhub-secret
    chart: ./dockerhub-secret
    values:
      - secretName: docker.io/radixdlt

  - name: postgres
    chart: bitnami/postgresql
    version:  12.12.10
    installed: {{ eq .Environment.Name "pr" }}
    values:
      - auth:
          postgresPassword: "secretString123"
          database: fullstack_dapp_example
        primary:
          persistence:
            enabled: false

  - name: redis
    chart: bitnami/redis
    version:  18.6.4
    values:
      - environments/common/redis.yaml

  - name: dapp
    chart: ./fullstack-chart
    values:
      - environments/common/dapp.yaml.gotmpl
      - environments/{{ .Environment.Name }}/dapp.yaml.gotmpl

  - name: admin
    chart: ./fullstack-chart
    needs:
      - dapp
    values:
      - environments/common/admin.yaml.gotmpl
      - environments/{{ .Environment.Name }}/admin.yaml.gotmpl

  - name: notification
    chart: ./fullstack-chart
    needs:
      - dapp
    values:
      - environments/common/notification.yaml.gotmpl
      - environments/{{ .Environment.Name }}/notification.yaml.gotmpl

  - name: transaction-stream
    chart: ./fullstack-chart
    needs:
      - dapp
    values:
      - environments/common/transaction-stream.yaml.gotmpl
      - environments/{{ .Environment.Name }}/transaction-stream.yaml.gotmpl

  - name: worker
    chart: ./fullstack-chart
    needs:
      - dapp
    values:
      - environments/common/worker.yaml.gotmpl
      - environments/{{ .Environment.Name }}/worker.yaml.gotmpl

  - name: redis-commander
    chart: ./redis-commander
    values:
      - environments/common/redis-commander.yaml.gotmpl

  - name: developer-access
    chart: rdx-works/developer-access
    version: 1.0.0
    values:
      - project: radquest
      - environments/common/developer-access.yaml.gotmpl

  - name: alertmanager
    chart: rdx-works/alertmanager-configs
    version: 1.1.0
    installed: {{ ne .Environment.Name "pr" }}
    values:
      - environments/{{ .Environment.Name }}/alertmanager.yaml.gotmpl
