apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  # name of ExternalSecret under CRD section
  name: dockerhub
  labels:
    {{- include "dockerhub-secret.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: main
    kind: ClusterSecretStore
  target:
    # name of actual secret under Config/Secrets, not required will use .metadata.name
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
  data:
  - secretKey: .dockerconfigjson
    remoteRef:
      key: {{ .Values.secretName }}
      version: "AWSCURRENT"
      property: dockerconfigjson
