{{- if .Values.metrics.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "radquest-notification.serviceAccountName" . }}
  labels:
    release: prometheus-operator
    {{- include "radquest-notification.labels" . | nindent 4 }}
spec:
  endpoints:
  - port: metrics
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace | quote }}
  selector:
    matchLabels:
      {{- include "radquest-notification.selectorLabels" . | nindent 6 }}
{{- end }}
