apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "radquest-dapp.fullname" . }}
  labels:
    {{- include "radquest-dapp.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "radquest-dapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "radquest-dapp.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "radquest-dapp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.enable_db_migrations }}
      initContainers:
        - name: db-migrations
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c", "-e"]
          args:
            - npx prisma migrate deploy --schema packages/database/prisma/schema.prisma
          env:
          {{- range $secret := .Values.secrets }}
          - name: {{ $secret.env_variable }}
            valueFrom:
              secretKeyRef:
                name: {{ $secret.external_secret_name }}
                key: {{ $secret.secret_key }}
          {{- end }}
          {{- range $key, $value := .Values.params }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- range $key, $value := .Values.params }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          {{- range $secret := .Values.secrets }}
          - name: {{ $secret.env_variable }}
            valueFrom:
              secretKeyRef:
                name: {{ $secret.external_secret_name }}
                key: {{ $secret.secret_key }}
          {{- end }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          {{- if .Values.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
              protocol: TCP
          {{- end }}
          {{- if .Values.pm2_metrics.enabled }}
            - name: pm2-metrics
              containerPort: {{ .Values.pm2_metrics.port }}
              protocol: TCP
          {{- end }}
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
