{{- range .Values.secrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: main
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
  data:
    - secretKey: {{ .secretName }}
      remoteRef:
        key: {{ .path }}
        {{- if .secretProperty }}
        property: {{ .secretProperty }}
        {{- end }}
{{- end }}