name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: RDXWorks-actions/checkout@main
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: RDXWorks-actions/setup-node@main
        with:
          node-version: "20.3.0"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          PUBLIC_NETWORK_ID: 2
