name: Helm changes

on:
  pull_request:
    paths:
      - "deploy/helm/**/*"
    branches:
      - main
  push:
    paths:
      - "deploy/helm/**/*"
    branches:
      - main

permissions:
  id-token: write
  pull-requests: write
  contents: read
  deployments: write
  packages: write

jobs:
  changed-files:
    name: Changed files
    runs-on: ubuntu-latest
    outputs:
      dev: ${{ steps.dev.outputs.any_changed }}
      mainnet: ${{ steps.mainnet.outputs.any_changed }}
    steps:
      - name: Checkout
        uses: RDXWorks-actions/checkout@main
        with:
          fetch-depth: 0

      - name: Check dev files
        id: dev
        uses: RDXWorks-actions/changed-files@main
        with:
          files: |
            deploy/helm/environments/dev/**
            deploy/helm/helmfile.yaml
            deploy/helm/admin/**/*
            deploy/helm/dapp/**/*
            deploy/helm/jetty-swap/**/*
            deploy/helm/letty-swap/**/*
            deploy/helm/notification/**/*
            deploy/helm/transaction-stream/**/*
            deploy/helm/worker/**/*

      - name: Check mainnet files
        id: mainnet
        uses: RDXWorks-actions/changed-files@main
        with:
          files: |
            deploy/helm/environments/mainnet/**
            deploy/helm/helmfile.yaml
            deploy/helm/admin/**/*
            deploy/helm/dapp/**/*
            deploy/helm/jetty-swap/**/*
            deploy/helm/letty-swap/**/*
            deploy/helm/notification/**/*
            deploy/helm/transaction-stream/**/*
            deploy/helm/worker/**/*

  diff_dev:
    name: DEV diff
    if: github.event.pull_request && needs.changed-files.outputs.dev == 'true'
    needs:
      - changed-files
    concurrency: 
      group: ${{ github.base_ref }}
      cancel-in-progress: false
    uses: radixdlt/public-iac-resuable-artifacts/.github/workflows/jenkins-deployment.yml@main
    with:
      github_branch: '${{ github.head_ref }}'
      jenkins_job_name: 'kubernetes-deployments/job/radquest'
      application_name: 'radquest'
      kubernetes_namespace: 'radquest-dev'
      aws_eks_cluster: 'rdx-works-main-dev'
      aws_iam_role_name: 'jenkins-radquest-dev-deployer'
      helmfile_environment: 'dev'
      helmfile_extra_vars: 'ci.tag=PLACEHOLDER'
      is_github_helm_changes_workflow: 'yes'
    secrets:
      aws_deployment_account_id: ${{ secrets.AWS_DEV_ACCOUNT_ID }}
      secrets_account_id: ${{ secrets.SECRETS_ACCOUNT_ID }}

  diff_deploy_mainnet:
    name: MAINNET diff and deploy
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.changed-files.outputs.mainnet == 'true'
    needs:
      - changed-files
    concurrency: 
      group: "release"
      cancel-in-progress: false
    uses: radixdlt/public-iac-resuable-artifacts/.github/workflows/jenkins-deployment.yml@main
    with:
      github_environment: 'mainnet'
      github_branch: '${{ github.ref }}'
      jenkins_job_name: 'kubernetes-deployments/job/radquest'
      application_name: 'radquest'
      kubernetes_namespace: 'radquest-mainnet'
      aws_eks_cluster: 'rtlj-prod'
      aws_iam_role_name: 'jenkins-radquest-mainnet-deployer'
      helmfile_environment: 'mainnet'
      helmfile_extra_vars: 'ci.tag=PLACEHOLDER'
      is_github_helm_changes_workflow: 'yes'
    secrets:
      aws_deployment_account_id: ${{ secrets.AWS_PROD_ACCOUNT_ID }}
      secrets_account_id: ${{ secrets.SECRETS_ACCOUNT_ID }}